version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
      
  - package-ecosystem: "npm"
    directory: "/docs"
    schedule:
      interval: "monthly"
      
  - package-ecosystem: "npm"
    directory: "/packages/embla-carousel-react-component"
    schedule:
      interval: "monthly"
      
  - package-ecosystem: "npm"
    directory: "/packages/eslint-config-custom"
    schedule:
      interval: "monthly"
